# : Manager [[[

[mgr]
cwd = { fg = "#ece0e0" }

# Tab
tab_active = { fg = "#531f2c", bg = "#ffb1c0", bold = true }
tab_inactive = { fg = "#ffd9df", bg = "#380a18" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#65de77", bg = "#65de77" }
marker_cut = { fg = "#b9f0c1", bg = "#b9f0c1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#9dd3a7", bg = "#9dd3a7" }

# Count
count_copied = { fg = "#00210c", bg = "#b9f0c1" }
count_cut = { fg = "#00210c", bg = "#b9f0c1" }
count_selected = { fg = "#531f2c", bg = "#9dd3a7" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb1c0" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#531f2c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb1c0", fg = "#531f2c", bold = true }
normal_alt  = { bg = "#524345", fg = "#d6c1c4" }

# Select mode
select_main = { bg = "#e5bcc3", fg = "#43292e", bold = true }
select_alt  = { bg = "#524345", fg = "#d6c1c4" }

# Unset mode
unset_main = { bg = "#9dd3a7", fg = "#013919", bold = true }
unset_alt  = { bg = "#524345", fg = "#d6c1c4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb1c0", bg = "#3f3738" }
progress_error = { fg = "#ffb4ab", bg = "#3f3738" }

# Permissions
permissions_t = { fg = "#ba4e60" }
permissions_w = { fg = "#439452" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3bd551" }
permissions_s = { fg = "#ff405e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb1c0" }
active = { fg = "#9dd3a7", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1c0" }
value = { fg = "#ece0e0" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb1c0", bold = true, bg = "#181213" }
inactive = { fg = "#e5bcc3", bg = "#181213" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb1c0", bg = "#531f2c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb1c0" }
title = {}
hovered = { fg = "#b9f0c1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3f3738" }
cand = { fg = "#ffb1c0" }
rest = { fg = "#531f2c" }
desc = { fg = "#ece0e0" }
separator = " ▶ "
separator_style = { fg = "#ece0e0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ece0e0" }
run = { fg = "#ece0e0" }
footer = { fg = "#43292e", bg = "#e5bcc3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#9dd3a7" }
title_warn = { fg = "#ffb1c0" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ece0e0" },
    { name = "*/", fg = "#ffb1c0" },
]

# : ]]]
