# : Manager [[[

[mgr]
cwd = { fg = "#dfe3e8" }

# Tab
tab_active = { fg = "#00344e", bg = "#8aceff", bold = true }
tab_inactive = { fg = "#c9e6ff", bg = "#001e2f" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffae4f", bg = "#ffae4f" }
marker_cut = { fg = "#ffddb5", bg = "#ffddb5" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffb958", bg = "#ffb958" }

# Count
count_copied = { fg = "#2a1800", bg = "#ffddb5" }
count_cut = { fg = "#2a1800", bg = "#ffddb5" }
count_selected = { fg = "#00344e", bg = "#ffb958" }

# Border
border_symbol = " "
border_style  = { fg = "#8aceff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#00344e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#8aceff", fg = "#00344e", bold = true }
normal_alt  = { bg = "#3f484f", fg = "#bfc7d1" }

# Select mode
select_main = { bg = "#aacae5", fg = "#103348", bold = true }
select_alt  = { bg = "#3f484f", fg = "#bfc7d1" }

# Unset mode
unset_main = { bg = "#ffb958", fg = "#462b00", bold = true }
unset_alt  = { bg = "#3f484f", fg = "#bfc7d1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8aceff", bg = "#353a3e" }
progress_error = { fg = "#ffb4ab", bg = "#353a3e" }

# Permissions
permissions_t = { fg = "#3a81bc" }
permissions_w = { fg = "#be6e00" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff971c" }
permissions_s = { fg = "#309fff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8aceff" }
active = { fg = "#ffb958", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#8aceff" }
value = { fg = "#dfe3e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#8aceff", bold = true, bg = "#101417" }
inactive = { fg = "#aacae5", bg = "#101417" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8aceff", bg = "#00344e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8aceff" }
title = {}
hovered = { fg = "#ffddb5", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a3e" }
cand = { fg = "#8aceff" }
rest = { fg = "#00344e" }
desc = { fg = "#dfe3e8" }
separator = " ▶ "
separator_style = { fg = "#dfe3e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe3e8" }
run = { fg = "#dfe3e8" }
footer = { fg = "#103348", bg = "#aacae5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffb958" }
title_warn = { fg = "#8aceff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dfe3e8" },
    { name = "*/", fg = "#8aceff" },
]

# : ]]]
