$image = /home/ducky/Pictures/Background/wallhaven-9oxme1.jpg


$background = rgba(101417ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d3135ff)

$inverse_primary = rgba(006491ff)

$inverse_surface = rgba(dfe3e8ff)

$on_background = rgba(dfe3e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(00344eff)

$on_primary_container = rgba(002235ff)

$on_primary_fixed = rgba(001e2fff)

$on_primary_fixed_variant = rgba(004c6eff)

$on_secondary = rgba(103348ff)

$on_secondary_container = rgba(c4e4ffff)

$on_secondary_fixed = rgba(001e2fff)

$on_secondary_fixed_variant = rgba(2a4a60ff)

$on_surface = rgba(dfe3e8ff)

$on_surface_variant = rgba(bfc7d1ff)

$on_tertiary = rgba(462b00ff)

$on_tertiary_container = rgba(2f1b00ff)

$on_tertiary_fixed = rgba(2a1800ff)

$on_tertiary_fixed_variant = rgba(643f00ff)

$outline = rgba(89929aff)

$outline_variant = rgba(3f484fff)

$primary = rgba(8aceffff)

$primary_container = rgba(53b3efff)

$primary_fixed = rgba(c9e6ffff)

$primary_fixed_dim = rgba(8aceffff)

$scrim = rgba(000000ff)

$secondary = rgba(aacae5ff)

$secondary_container = rgba(2a4a60ff)

$secondary_fixed = rgba(c9e6ffff)

$secondary_fixed_dim = rgba(aacae5ff)

$shadow = rgba(000000ff)

$source_color = rgba(53b3efff)

$surface = rgba(101417ff)

$surface_bright = rgba(353a3eff)

$surface_container = rgba(1c2024ff)

$surface_container_high = rgba(262a2eff)

$surface_container_highest = rgba(313539ff)

$surface_container_low = rgba(181c20ff)

$surface_container_lowest = rgba(0a0f12ff)

$surface_dim = rgba(101417ff)

$surface_tint = rgba(8aceffff)

$surface_variant = rgba(3f484fff)

$tertiary = rgba(ffb958ff)

$tertiary_container = rgba(e39c31ff)

$tertiary_fixed = rgba(ffddb5ff)

$tertiary_fixed_dim = rgba(ffb958ff)

