$image = /home/ducky/Pictures/Background/QvevW8JVDf.png


$background = rgba(181213ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(362f30ff)

$inverse_primary = rgba(8a4c59ff)

$inverse_surface = rgba(ece0e0ff)

$on_background = rgba(ece0e0ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(531f2cff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(380a18ff)

$on_primary_fixed_variant = rgba(6e3542ff)

$on_secondary = rgba(43292eff)

$on_secondary_container = rgba(ffdbe0ff)

$on_secondary_fixed = rgba(2c151aff)

$on_secondary_fixed_variant = rgba(5c3f44ff)

$on_surface = rgba(ece0e0ff)

$on_surface_variant = rgba(d6c1c4ff)

$on_tertiary = rgba(013919ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(00210cff)

$on_tertiary_fixed_variant = rgba(1e502eff)

$outline = rgba(9f8c8fff)

$outline_variant = rgba(524345ff)

$primary = rgba(ffb1c0ff)

$primary_container = rgba(c47d8bff)

$primary_fixed = rgba(ffd9dfff)

$primary_fixed_dim = rgba(ffb1c0ff)

$scrim = rgba(000000ff)

$secondary = rgba(e5bcc3ff)

$secondary_container = rgba(5f4146ff)

$secondary_fixed = rgba(ffd9dfff)

$secondary_fixed_dim = rgba(e5bcc3ff)

$shadow = rgba(000000ff)

$source_color = rgba(ba7482ff)

$surface = rgba(181213ff)

$surface_bright = rgba(3f3738ff)

$surface_container = rgba(241e1fff)

$surface_container_high = rgba(2f2829ff)

$surface_container_highest = rgba(3a3334ff)

$surface_container_low = rgba(201a1bff)

$surface_container_lowest = rgba(120d0eff)

$surface_dim = rgba(181213ff)

$surface_tint = rgba(ffb1c0ff)

$surface_variant = rgba(524345ff)

$tertiary = rgba(9dd3a7ff)

$tertiary_container = rgba(699c74ff)

$tertiary_fixed = rgba(b9f0c1ff)

$tertiary_fixed_dim = rgba(9dd3a7ff)

